const TOPICS = [
  { id: "01", title: "What Git Tracks" },
  { id: "02", title: "Install and Configure" },
  { id: "03", title: "Repositories and Commits" },
  { id: "04", title: "Branches and Merges" },
  { id: "05", title: "GitHub Remotes and Auth" },
  { id: "06", title: "Pull Requests and Collaboration" },
  { id: "07", title: "Security Hygiene and Secrets" },
  { id: "08", title: "Cybersecurity Workflows" },
  { id: "mixed", title: "Mixed Review" }
];

const QUIZ_CONFIG = { defaultAttempt: 15, attempt: { mixed: 50 } };

const QUESTIONS = {
  "01": [
    { q: "What is Git primarily used for?", options: ["Version control", "Packet capture", "Password cracking", "Firewall routing"], answer: 0, explain: "Git records file history as commits so changes can be reviewed and recovered." },
    { q: "Which command shows the current working tree state?", options: ["git status", "git push", "git clone", "git init --bare"], answer: 0, explain: "git status shows tracked, staged, modified, and untracked files." },
    { q: "What is the staging area?", options: ["The selected changes for the next commit", "The GitHub website", "A deleted branch", "A remote server"], answer: 0, explain: "The staging area holds exactly what you plan to save in the next commit." },
    { q: "Why is Git useful for cybersecurity notes?", options: ["It provides a change history", "It encrypts all files automatically", "It blocks all malware", "It replaces backups completely"], answer: 0, explain: "Git helps preserve a traceable record of notes, scripts, and lab documentation." },
    { q: "Which command displays commit history?", options: ["git log", "git add", "git remote", "git switch"], answer: 0, explain: "git log shows previous commits." },
    { q: "What does Git record to help you understand file history?", options: ["Snapshots of changes over time", "Live network packets", "Encrypted password vaults", "Firewall configuration rules"], answer: 0, explain: "Git tracks history as a series of snapshots, not live traffic or firewall state." },
    { q: "Which area of Git holds the files you are currently editing?", options: ["Working tree", "Staging area", "Repository", "Remote server"], answer: 0, explain: "The working tree is where you actively edit files before staging or committing them." },
    { q: "Which area of Git holds saved commits and history?", options: ["Repository", "Working tree", "Staging area", "GitHub Issues"], answer: 0, explain: "The repository stores the committed history of the project." },
    { q: "In the notes' table, which command is paired with the staging area?", options: ["git add", "git status", "git log", "git clone"], answer: 0, explain: "git add moves changes from the working tree into the staging area." },
    { q: "In the notes' table, which command is paired with the repository?", options: ["git log", "git add", "git status", "git diff"], answer: 0, explain: "git log reads the commit history stored in the repository." },
    { q: "What is the correct order of the daily loop shown in the notes?", options: ["git status, git add, git commit", "git commit, git add, git status", "git add, git commit, git status", "git status, git commit, git add"], answer: 0, explain: "The notes show checking status, staging changes, then committing them." },
    { q: "Which of these is listed as something Git helps preserve for security work?", options: ["Detection rules and why they changed", "Live memory dumps", "Firewall port states", "Wireless signal strength"], answer: 0, explain: "The notes call out detection rule history as one of the things Git helps preserve." },
    { q: "Which of these is listed as something Git helps preserve for security work?", options: ["Scripts used for scanning, parsing, or reporting", "Router firmware binaries", "Cloud billing invoices", "Screen brightness settings"], answer: 0, explain: "Git is described as useful for tracking scripts used in security tasks." },
    { q: "Which of these is listed as something Git helps preserve for security work?", options: ["Incident notes without overwriting earlier observations", "Encrypted disk images only", "Deleted browser history", "Live packet streams"], answer: 0, explain: "The notes mention keeping incident notes without overwriting earlier observations." },
    { q: "Per the notes' tip, what should a good commit message explain?", options: ["The reason for the change", "Only the file name", "The author's mood", "The current date"], answer: 0, explain: "The tip says a commit message should explain why the change was made, not only the file name." },
    { q: "What does Git give you for notes, scripts, detections, and writeups, according to the notes?", options: ["An audit trail", "A firewall", "A password manager", "A malware scanner"], answer: 0, explain: "Git provides an audit trail of changes over time." },
    { q: "How is Git described at its core in the notes?", options: ["A local version control system", "A cloud-only backup service", "A network intrusion detector", "A password vault"], answer: 0, explain: "The notes describe Git as a local version control system." },
    { q: "Which command would you run first to see what changed before staging?", options: ["git status", "git commit", "git push", "git clone"], answer: 0, explain: "git status is the first step in the daily loop, showing what changed." },
    { q: "What best describes a Git commit?", options: ["A saved snapshot of staged changes", "A live network connection", "A deleted branch", "A remote server address"], answer: 0, explain: "A commit saves a snapshot of what was staged at that point." },
    { q: "Which area sits between the working tree and the repository?", options: ["Staging area", "Remote", "Issue tracker", "Pull request"], answer: 0, explain: "The staging area is the middle step where changes are selected before committing." }
  ],
  "02": [
    { q: "Which setting controls the author name on commits?", options: ["user.name", "core.name", "commit.author", "github.user"], answer: 0, explain: "user.name is the Git config key for the displayed author name." },
    { q: "Which default branch name is commonly used for new repositories?", options: ["main", "primary", "trunk-only", "production"], answer: 0, explain: "main is the common default branch name for modern GitHub repos." },
    { q: "What does pull.ff only help prevent?", options: ["Accidental merge commits during pull", "All network access", "Untracked files", "GitHub issues"], answer: 0, explain: "It allows pulls only when Git can fast-forward the branch." },
    { q: "Why should you choose a public-safe email for public commits?", options: ["Commit metadata can be visible", "Git requires a school email", "GitHub rejects private domains", "It makes commits encrypted"], answer: 0, explain: "Author email can appear in commit metadata." },
    { q: "Which command lists global Git configuration?", options: ["git config --global --list", "git global", "git status --global", "git list config"], answer: 0, explain: "git config --global --list prints global settings." },
    { q: "Which command sets your commit author email?", options: ["git config --global user.email \"you@example.com\"", "git config --global core.email", "git config --global commit.email", "git config --global github.email"], answer: 0, explain: "user.email is the config key that sets the email attached to commits." },
    { q: "Which config sets the default branch name for new repositories?", options: ["git config --global init.defaultBranch main", "git config --global branch.main", "git config --global core.branch main", "git config --global default.branch"], answer: 0, explain: "init.defaultBranch controls what new repos are named when initialized." },
    { q: "What does core.autocrlf true help manage?", options: ["Line ending conversion", "Commit author identity", "Remote authentication", "Branch naming"], answer: 0, explain: "core.autocrlf manages line-ending conversion between operating systems." },
    { q: "What does fetch.prune true do?", options: ["Cleans up remote-tracking branch references that were deleted", "Deletes local uncommitted files", "Removes commit history permanently", "Disables authentication prompts"], answer: 0, explain: "fetch.prune removes stale references to remote branches that no longer exist." },
    { q: "Which command checks your current global Git configuration?", options: ["git config --global --list", "git status --global", "git list --config", "git global --show"], answer: 0, explain: "git config --global --list prints all global settings." },
    { q: "Which two settings should you configure right after installing Git?", options: ["user.name and user.email", "core.autocrlf and fetch.prune", "pull.ff and init.defaultBranch", "origin and upstream"], answer: 0, explain: "The notes show setting user.name and user.email as the first setup step." },
    { q: "Per the Security-minded Setup section, what should you avoid storing in command history or repo files?", options: ["Tokens", "Branch names", "Commit messages", "File extensions"], answer: 0, explain: "Tokens should never be stored in command history or repo files." },
    { q: "What does the notes recommend about identities for school/public versus employer/client work?", options: ["Keep them separate if needed", "Always use the same identity everywhere", "Never configure user.email", "Use only anonymous emails"], answer: 0, explain: "The notes suggest keeping separate identities for different contexts when needed." },
    { q: "Which authentication approach does the notes recommend using?", options: ["Methods recommended by your organization", "Whatever is fastest to type", "Shared team passwords", "No authentication at all"], answer: 0, explain: "The notes recommend using GitHub authentication methods your organization recommends." },
    { q: "What is one reason to choose a public-safe email address for commits?", options: ["Commit metadata can be visible publicly", "GitHub requires a school email", "Git encrypts the email automatically", "It changes your username"], answer: 0, explain: "Author email appears in commit metadata, which can be publicly visible." },
    { q: "Which setting avoids accidental merge commits when pulling?", options: ["pull.ff only", "fetch.prune true", "core.autocrlf true", "init.defaultBranch main"], answer: 0, explain: "pull.ff only allows pulls only when a fast-forward is possible, avoiding surprise merge commits." },
    { q: "Complete the command: git config --global init.defaultBranch ____", options: ["main", "master", "trunk", "release"], answer: 0, explain: "The notes use main as the modern default branch name." },
    { q: "What is the purpose of running git config --global --list after setup?", options: ["To verify the configuration took effect", "To delete the configuration", "To push commits", "To create a new branch"], answer: 0, explain: "Listing the config confirms your settings were applied correctly." },
    { q: "Which of these is NOT one of the initial identity commands shown in the notes?", options: ["git config --global core.editor vim", "git config --global user.name \"Your Name\"", "git config --global user.email \"you@example.com\"", "git config --global init.defaultBranch main"], answer: 0, explain: "The notes' first-time setup block does not mention core.editor." },
    { q: "Which useful default is shown alongside core.autocrlf and pull.ff only?", options: ["fetch.prune true", "commit.gpgsign true", "merge.tool meld", "diff.context 10"], answer: 0, explain: "fetch.prune true is listed as one of the useful defaults in the notes." }
  ],
  "03": [
    { q: "Which command creates a new Git repository in the current folder?", options: ["git init", "git start", "git new", "git track"], answer: 0, explain: "git init initializes a repository." },
    { q: "Which command stages a file?", options: ["git add README.md", "git save README.md", "git push README.md", "git stage --remote README.md"], answer: 0, explain: "git add adds changes to the staging area." },
    { q: "Which command shows unstaged file differences?", options: ["git diff", "git remote -v", "git clone", "git branch -d"], answer: 0, explain: "git diff shows changes that are not staged by default." },
    { q: "What makes a good commit message?", options: ["It clearly describes the change", "It is always one word", "It hides the reason", "It includes passwords for context"], answer: 0, explain: "Clear commit messages make history review easier." },
    { q: "Why stage files intentionally?", options: ["To avoid committing unrelated or sensitive files", "To delete history", "To bypass GitHub auth", "To make files private"], answer: 0, explain: "Intentional staging reduces accidental commits." },
    { q: "Which command clones an existing repository?", options: ["git clone https://github.com/user/repo.git", "git init --remote", "git fetch --new", "git pull --clone"], answer: 0, explain: "git clone copies an existing remote repository to your machine." },
    { q: "What is the correct sequence to start a brand-new local repo, per the notes?", options: ["mkdir security-notes, cd security-notes, git init", "git init, mkdir security-notes, cd security-notes", "cd security-notes, git init, mkdir security-notes", "git clone, mkdir security-notes, cd security-notes"], answer: 0, explain: "The notes show creating the folder, moving into it, then initializing the repo." },
    { q: "Which command shows staged differences specifically?", options: ["git diff --staged", "git diff", "git status --staged", "git log --staged"], answer: 0, explain: "git diff --staged compares the staging area to the last commit." },
    { q: "Which command commits staged changes with a message?", options: ["git commit -m \"Add lab overview\"", "git add -m \"Add lab overview\"", "git push -m \"Add lab overview\"", "git init -m \"Add lab overview\""], answer: 0, explain: "git commit -m creates a commit with an inline message." },
    { q: "Why might a lab folder need intentional staging, per the notes?", options: ["It may contain both safe notes and sensitive artifacts", "Git requires exactly one file per commit", "Staging is required before cloning", "GitHub deletes unstaged files automatically"], answer: 0, explain: "Mixed folders of safe and sensitive files make intentional staging important." },
    { q: "Which of these is a strong, specific commit message example from the notes?", options: ["\"Add SSH hardening checklist\"", "\"updates\"", "\"stuff\"", "\"final\""], answer: 0, explain: "This message is short, specific, and action-oriented, unlike the vague examples." },
    { q: "Which of these is a strong, specific commit message example from the notes?", options: ["\"Document Nmap scan methodology\"", "\"final\"", "\"stuff\"", "\"updates\""], answer: 0, explain: "This is one of the strong commit message examples given in the notes." },
    { q: "Which of these is a strong, specific commit message example from the notes?", options: ["\"Fix Sigma rule false positive note\"", "\"updates\"", "\"final\"", "\"stuff\""], answer: 0, explain: "This message clearly states what was fixed, matching the notes' good examples." },
    { q: "Which of these is called out as a vague commit message to avoid?", options: ["\"updates\"", "\"Add lab overview\"", "\"Document Nmap scan methodology\"", "\"Fix Sigma rule false positive note\""], answer: 0, explain: "The notes explicitly list \"updates\" as a message to avoid." },
    { q: "Which of these is called out as a vague commit message to avoid?", options: ["\"stuff\"", "\"Add SSH hardening checklist\"", "\"Add lab overview\"", "\"Document Nmap scan methodology\""], answer: 0, explain: "\"stuff\" is listed as an example of a vague message to avoid." },
    { q: "Which of these is called out as a vague commit message to avoid?", options: ["\"final\"", "\"Fix Sigma rule false positive note\"", "\"Add SSH hardening checklist\"", "\"Add lab overview\""], answer: 0, explain: "\"final\" is listed as an example of a vague message to avoid." },
    { q: "What should you check before staging files, per the workflow shown in the notes?", options: ["git status and git diff", "git push and git pull", "git clone and git init", "git log and git remote"], answer: 0, explain: "The notes show running git status and git diff before staging anything." },
    { q: "What does git diff show by default, before staging?", options: ["Unstaged changes", "Staged changes only", "The commit history", "Remote branch names"], answer: 0, explain: "Without --staged, git diff shows changes not yet staged." },
    { q: "What is the full workflow order shown in the notes for staging and committing?", options: ["status, diff, add, diff --staged, commit", "commit, add, diff, status", "add, commit, status, diff", "diff --staged, status, add, commit"], answer: 0, explain: "The notes demonstrate this exact sequence for careful staging." },
    { q: "Why are action-oriented commit messages preferred, per the notes?", options: ["They are short, specific, and describe the action taken", "They must always contain a date", "They hide the actual change", "They must be exactly one word"], answer: 0, explain: "The notes describe strong messages as short, specific, and action-oriented." },
    { q: "What is a risk of staging an entire folder without review in a security context?", options: ["You might accidentally commit sensitive artifacts", "Git will refuse the commit", "The repository becomes read-only", "GitHub will delete the folder"], answer: 0, explain: "Careless staging can pull in sensitive files mixed in with safe notes." },
    { q: "Which command would confirm a file was successfully staged before committing?", options: ["git status", "git clone", "git remote -v", "git branch"], answer: 0, explain: "git status shows which files are currently staged." },
    { q: "When cloning a repository, what must you provide?", options: ["The repository's URL", "A commit message", "A branch name only", "A staging area path"], answer: 0, explain: "git clone requires the URL of the repository to copy." },
    { q: "What does \"intentional staging\" mean in practice?", options: ["Reviewing and selecting exactly which changes to include", "Committing every file automatically", "Skipping git status before committing", "Cloning before initializing"], answer: 0, explain: "Intentional staging means deliberately choosing what goes into the next commit." },
    { q: "Which phrase best completes: a commit message should be short, specific, and ____?", options: ["action-oriented", "encrypted", "anonymous", "randomized"], answer: 0, explain: "The notes describe good commit messages as short, specific, and action-oriented." }
  ],
  "04": [
    { q: "What is a Git branch?", options: ["A pointer to a line of work", "A backup service", "A GitHub password", "A file extension"], answer: 0, explain: "A branch points to a commit and moves as work is added." },
    { q: "Which command creates and switches to a branch?", options: ["git switch -c new-branch", "git branch --upload new-branch", "git merge -c new-branch", "git remote add new-branch"], answer: 0, explain: "git switch -c creates a branch and checks it out." },
    { q: "Why use branches for incident notes?", options: ["To isolate draft work", "To expose evidence publicly", "To erase history", "To skip reviews"], answer: 0, explain: "Branches keep work separate until it is ready." },
    { q: "When can a merge conflict occur?", options: ["When changes overlap and Git cannot combine them automatically", "Only when GitHub is offline", "Only when a file is empty", "Whenever a branch is pushed"], answer: 0, explain: "Conflicts happen when Git needs human judgment to combine edits." },
    { q: "Which command shows a compact branch graph?", options: ["git log --oneline --graph --decorate", "git status --graph", "git diff --remote", "git merge --draw"], answer: 0, explain: "This log command is useful for visualizing history." },
    { q: "Which command switches back to the main branch?", options: ["git switch main", "git merge main", "git branch main", "git remote main"], answer: 0, explain: "git switch main checks out the main branch." },
    { q: "What should you run before merging, to make sure main is up to date?", options: ["git pull --ff-only", "git push --force", "git branch -d main", "git clone main"], answer: 0, explain: "The notes show running git pull --ff-only before merging." },
    { q: "Which command merges a feature branch into the current branch?", options: ["git merge add-linux-hardening-notes", "git switch add-linux-hardening-notes", "git branch add-linux-hardening-notes", "git remote add-linux-hardening-notes"], answer: 0, explain: "git merge combines the named branch into the current branch." },
    { q: "What is the correct order of the merge workflow shown in the notes?", options: ["switch main, pull --ff-only, merge branch", "merge branch, switch main, pull --ff-only", "pull --ff-only, merge branch, switch main", "switch main, merge branch, pull --ff-only"], answer: 0, explain: "The notes show switching to main, pulling, then merging the feature branch." },
    { q: "Which of these is an example branch naming convention from the notes?", options: ["notes/ssh-hardening", "branch1", "temp", "my-work"], answer: 0, explain: "notes/ssh-hardening follows the prefix/topic naming style shown in the notes." },
    { q: "Which of these is an example branch naming convention from the notes?", options: ["lab/nmap-baseline", "branch2", "final-branch", "new-stuff"], answer: 0, explain: "lab/nmap-baseline is one of the example branch names given." },
    { q: "Which of these is an example branch naming convention from the notes?", options: ["fix/broken-link", "misc", "temp-fix", "branch-x"], answer: 0, explain: "fix/broken-link is one of the example branch names given in the notes." },
    { q: "Which of these is an example branch naming convention from the notes?", options: ["incident/timeline-draft", "draft1", "wip", "branch-final"], answer: 0, explain: "incident/timeline-draft matches the naming convention shown in the notes." },
    { q: "What is the first step in resolving a merge conflict, per the notes?", options: ["Opening the conflicted file", "Deleting the branch", "Force-pushing to main", "Cloning the repo again"], answer: 0, explain: "The notes list opening the conflicted file as the first resolution step." },
    { q: "What is the final step in resolving a merge conflict, per the notes?", options: ["Staging and committing the resolution", "Deleting the conflicting branch", "Reverting to the previous commit", "Renaming the file"], answer: 0, explain: "After resolving the conflict, you stage and commit the result." },
    { q: "What must you remove from a file before committing a conflict resolution?", options: ["Conflict markers", "The file extension", "The commit message", "The branch name"], answer: 0, explain: "Conflict markers must be removed once you've chosen the correct content." },
    { q: "According to the note in the chapter, what should you NOT do when resolving conflicts in security documentation?", options: ["Delete useful investigation notes without being sure they're duplicated elsewhere", "Open the conflicted file", "Stage the resolved file", "Commit the resolution"], answer: 0, explain: "The note warns against deleting useful investigation notes carelessly during conflict resolution." },
    { q: "Why is preserving evidence chronology important in security docs, per the notes?", options: ["Careless conflict resolution could lose useful investigation notes", "Git automatically deletes old evidence", "Chronology has no effect on investigations", "Evidence order is only cosmetic"], answer: 0, explain: "The notes stress preserving chronology so investigation notes aren't lost during conflict cleanup." },
    { q: "What is a branch, conceptually, per the notes?", options: ["A movable pointer to a line of work", "A copy of the entire GitHub website", "A type of commit message", "A permanent, unchangeable snapshot"], answer: 0, explain: "The notes define a branch as a movable pointer to a line of work." },
    { q: "Why use a branch before merging into main, per the notes?", options: ["To isolate changes before they become part of main", "To make the repository public", "To delete unwanted commits", "To bypass authentication"], answer: 0, explain: "Branches isolate work until it's ready to join main." },
    { q: "Which command both creates and checks out a new branch in one step?", options: ["git switch -c add-linux-hardening-notes", "git branch add-linux-hardening-notes", "git merge -c add-linux-hardening-notes", "git remote -c add-linux-hardening-notes"], answer: 0, explain: "The -c flag with git switch creates and checks out the branch together." },
    { q: "What causes Git to be unable to automatically combine changes?", options: ["Overlapping edits that Git cannot merge automatically", "Having more than one branch", "Using git status too often", "Cloning a repository twice"], answer: 0, explain: "Conflicts arise when overlapping edits can't be automatically reconciled." },
    { q: "Which step comes right after choosing the correct final content when resolving a conflict?", options: ["Removing conflict markers", "Deleting the branch", "Pushing to origin", "Renaming the file"], answer: 0, explain: "After picking the correct content, you remove the conflict markers next." },
    { q: "What kind of branch name would best fit documenting a new incident timeline, per the notes' convention?", options: ["incident/timeline-draft", "main", "fix", "branch99"], answer: 0, explain: "incident/timeline-draft follows the notes' naming convention for incident work." },
    { q: "Which of these branch names would NOT follow the notes' prefix/topic naming convention?", options: ["branch1", "notes/ssh-hardening", "lab/nmap-baseline", "fix/broken-link"], answer: 0, explain: "The notes favor descriptive prefix/topic names like notes/ssh-hardening rather than generic names like branch1." }
  ],
  "05": [
    { q: "What is a Git remote?", options: ["A named link to another repository copy", "A secret scanner", "A commit message", "A local-only branch"], answer: 0, explain: "A remote usually points to GitHub or another shared repo host." },
    { q: "What is the conventional name for the main remote?", options: ["origin", "main", "upstream-main", "server"], answer: 0, explain: "origin is the default conventional remote name." },
    { q: "Which command lists configured remotes?", options: ["git remote -v", "git list origins", "git status --remote-only", "git auth"], answer: 0, explain: "git remote -v prints remote names and URLs." },
    { q: "What does git push -u origin main do?", options: ["Pushes main and sets upstream tracking", "Deletes origin", "Creates a local-only branch", "Disables authentication"], answer: 0, explain: "The -u option sets the upstream so future push and pull are simpler." },
    { q: "How should tokens be treated?", options: ["Like passwords", "Like public usernames", "Like commit messages", "Like branch names"], answer: 0, explain: "Tokens can grant account or repository access." },
    { q: "What does \"origin\" conventionally refer to?", options: ["The main/default remote of a repository", "A local-only branch", "A commit message template", "A GitHub username"], answer: 0, explain: "origin is the conventional name for a repository's primary remote." },
    { q: "Which command adds a new remote named origin?", options: ["git remote add origin https://github.com/ijk37/git-github.git", "git remote origin https://github.com/ijk37/git-github.git", "git clone add origin", "git push add origin"], answer: 0, explain: "git remote add origin <url> registers a new remote under that name." },
    { q: "After upstream tracking is set, which command pushes normally?", options: ["git push", "git push -u origin main", "git remote -v", "git clone"], answer: 0, explain: "Once upstream is set, a plain git push is enough." },
    { q: "After upstream tracking is set, which command pulls with fast-forward only?", options: ["git pull --ff-only", "git push --ff-only", "git fetch --force", "git merge --ff-only"], answer: 0, explain: "git pull --ff-only fetches and fast-forwards without creating a merge commit." },
    { q: "Which authentication method is described as working well with credential helpers and tokens?", options: ["HTTPS", "SSH", "FTP", "Telnet"], answer: 0, explain: "The notes describe HTTPS as common and compatible with credential helpers and tokens." },
    { q: "Which authentication method is described as useful for frequent GitHub use with key-based auth?", options: ["SSH", "HTTPS", "FTP", "Telnet"], answer: 0, explain: "SSH is noted as useful for frequent use with key-based authentication." },
    { q: "What should you NEVER paste into a repo file, per the notes?", options: ["A personal access token", "A README description", "A branch name", "A commit hash"], answer: 0, explain: "The notes warn against ever pasting a personal access token into a repo file." },
    { q: "What permission scope should tokens be given, per the notes?", options: ["The smallest permission scope possible", "Full admin access always", "Owner-level access to all repos", "No scope restriction is needed"], answer: 0, explain: "Tokens should be scoped as narrowly as possible to limit risk." },
    { q: "When should you rotate a token, per the notes?", options: ["If a machine is lost, shared, or compromised", "Every time you push a commit", "Only when GitHub asks", "Never, tokens don't need rotation"], answer: 0, explain: "The notes recommend rotating tokens after loss, sharing, or compromise of a machine." },
    { q: "What is a Git remote, fundamentally?", options: ["A named link to another copy of the repository", "A local backup folder", "A type of commit", "A branch naming convention"], answer: 0, explain: "A remote is a named reference to another copy of the repo, often on GitHub." },
    { q: "Where is a remote usually hosted, per the notes?", options: ["GitHub", "A USB drive", "A printed document", "An email inbox"], answer: 0, explain: "The notes describe remotes as usually pointing to GitHub." },
    { q: "Which flag in \"git push -u origin main\" sets up upstream tracking?", options: ["-u", "-v", "-f", "-b"], answer: 0, explain: "The -u flag sets the upstream branch for future pushes and pulls." },
    { q: "Why is setting the upstream tracking branch useful, per the notes?", options: ["It makes future push and pull commands simpler", "It deletes the local branch", "It encrypts commits", "It renames the repository"], answer: 0, explain: "Once upstream is set, you can run plain git push/git pull afterward." },
    { q: "Which command lists the URLs of all configured remotes?", options: ["git remote -v", "git branch -v", "git log -v", "git status -v"], answer: 0, explain: "git remote -v prints remote names alongside their URLs." },
    { q: "What should tokens be treated like, according to the notes?", options: ["Passwords", "Public usernames", "Commit messages", "Branch names"], answer: 0, explain: "The notes say tokens can grant access, so they should be treated like passwords." },
    { q: "Which authentication method do the notes describe as common and works with credential helpers?", options: ["HTTPS", "SSH", "Telnet", "FTP"], answer: 0, explain: "HTTPS is described as common and compatible with credential helpers." },
    { q: "What is the risk of giving a token overly broad permissions?", options: ["It increases damage if the token is leaked", "It slows down git commands", "It prevents cloning", "It disables branch creation"], answer: 0, explain: "Broader token scope means more damage potential if it's exposed." },
    { q: "What action should follow if a work machine holding a token is lost?", options: ["Rotate the token", "Ignore it since tokens expire automatically", "Delete the repository", "Rename the branch"], answer: 0, explain: "A lost machine means the token should be rotated immediately." },
    { q: "Fill in the blank: git push -u origin ____", options: ["main", "origin", "HEAD~1", "remote"], answer: 0, explain: "The notes show pushing and tracking the main branch." },
    { q: "Which of the following is NOT one of the authentication habits listed in the notes?", options: ["Share tokens across all team members for convenience", "Never paste a personal access token into a repo file", "Treat tokens like passwords", "Give tokens the smallest permission scope possible"], answer: 0, explain: "The notes never recommend sharing tokens broadly; all the other options are actual habits listed." }
  ],
  "06": [
    { q: "What is a pull request?", options: ["A request to review and merge branch changes", "A password reset", "A local commit only", "A clone command"], answer: 0, explain: "Pull requests support review, discussion, and checks before merging." },
    { q: "Which command compares your branch to main?", options: ["git diff main...HEAD", "git push main...HEAD", "git add main...HEAD", "git clone main...HEAD"], answer: 0, explain: "git diff main...HEAD shows changes introduced by your branch." },
    { q: "What should reviewers check in security repos?", options: ["Secrets and sensitive evidence exposure", "Only font size", "Only branch color", "Only commit count"], answer: 0, explain: "Review should include security and privacy risk." },
    { q: "What are GitHub issues useful for?", options: ["Tracking tasks and questions", "Storing API keys", "Replacing commits", "Compiling code"], answer: 0, explain: "Issues help organize work and discussions." },
    { q: "Why run checks before merging?", options: ["To catch mistakes earlier", "To erase commit authors", "To make the repo private", "To skip review"], answer: 0, explain: "Automated checks and human review reduce mistakes." },
    { q: "Which command shows the commit log unique to your branch before opening a PR?", options: ["git log --oneline main..HEAD", "git log --oneline HEAD..main", "git status main..HEAD", "git diff --staged main..HEAD"], answer: 0, explain: "This range shows commits on your branch not yet on main." },
    { q: "Which of these is listed as a use case for pull requests in security teams?", options: ["Detection rule reviews", "Password sharing", "Deleting evidence", "Disabling authentication"], answer: 0, explain: "The notes list detection rule reviews as a PR use case for security teams." },
    { q: "Which of these is listed as a use case for pull requests in security teams?", options: ["Infrastructure-as-code changes", "Personal photo uploads", "Deleting all issues", "Renaming GitHub accounts"], answer: 0, explain: "IaC changes are listed as a security-team PR use case." },
    { q: "Which of these is listed as a use case for pull requests in security teams?", options: ["Incident report edits", "Disabling branch protection", "Publishing raw secrets", "Deleting commit history"], answer: 0, explain: "Incident report edits are listed as a PR use case in the notes." },
    { q: "Which of these is listed as a use case for pull requests in security teams?", options: ["Script and tooling updates", "Sharing personal passwords", "Removing all reviewers", "Disabling checks"], answer: 0, explain: "Script and tooling updates are listed as a PR use case." },
    { q: "What should you run to check your working tree before opening a PR?", options: ["git status", "git remote -v", "git clone", "git branch -d"], answer: 0, explain: "git status confirms your working tree is clean before opening a PR." },
    { q: "Which reviewer question relates to reproducibility, per the notes?", options: ["Are commands reproducible?", "Is the font consistent?", "Is the repo public?", "Is the branch renamed?"], answer: 0, explain: "One reviewer checklist item asks whether commands are reproducible." },
    { q: "Which reviewer question relates to assumptions, per the notes?", options: ["Are assumptions documented?", "Is the README colorful?", "Is the branch deleted?", "Is the commit signed?"], answer: 0, explain: "Reviewers are asked to check whether assumptions are documented." },
    { q: "Which reviewer question relates to scope, per the notes?", options: ["Does the change match the stated purpose?", "Is the PR title emoji-free?", "Is the branch protected?", "Is the repository starred?"], answer: 0, explain: "Reviewers check whether the change matches its stated purpose." },
    { q: "What does a pull request give collaborators a place to do?", options: ["Review diffs, discuss risks, and run checks", "Delete the repository", "Bypass authentication", "Rename the organization"], answer: 0, explain: "PRs provide a space for review, discussion, and automated checks." },
    { q: "Which of these is an example of a specific, useful issue title from the notes?", options: ["\"Document SSH key setup for Windows\"", "\"fix stuff\"", "\"todo\"", "\"help\""], answer: 0, explain: "This is one of the specific issue titles given as a good example." },
    { q: "Which of these is an example of a specific, useful issue title from the notes?", options: ["\"Add .gitignore pattern for packet captures\"", "\"todo\"", "\"fix stuff\"", "\"misc\""], answer: 0, explain: "This is one of the specific issue titles given as a good example." },
    { q: "Which of these is an example of a specific, useful issue title from the notes?", options: ["\"Review secret scanning options\"", "\"help\"", "\"misc\"", "\"todo\""], answer: 0, explain: "This is one of the specific issue titles given as a good example." },
    { q: "What are GitHub issues useful for tracking, per the notes?", options: ["Tasks, bugs, research questions, and lab TODOs", "Encrypted secrets", "Deleted commits", "Remote server passwords"], answer: 0, explain: "Issues track tasks, bugs, research questions, and TODOs." },
    { q: "Why keep issue titles specific, per the notes?", options: ["So the task is clear and actionable", "Because GitHub limits title length to one word", "Because vague titles are deleted automatically", "Because specific titles hide sensitive data"], answer: 0, explain: "Specific titles make issues clear and actionable." },
    { q: "What kind of documentation changes benefit from peer review, per the notes?", options: ["Ones that need review before merging", "Only spelling fixes", "Only image changes", "None, docs don't need review"], answer: 0, explain: "The notes list documentation changes needing peer review as a PR use case." },
    { q: "Which command range syntax compares your branch against main for review?", options: ["main...HEAD", "HEAD===main", "main<->HEAD", "main::HEAD"], answer: 0, explain: "git diff main...HEAD shows changes introduced by your branch." }
  ],
  "07": [
    { q: "Which file can prevent common sensitive files from being added accidentally?", options: [".gitignore", "README.md", "LICENSE", "index.html"], answer: 0, explain: ".gitignore tells Git which untracked files to ignore." },
    { q: "Which item should not be committed to a public repo?", options: ["Private key", "Sanitized README", "Generic checklist", "Learning notes"], answer: 0, explain: "Private keys are sensitive credentials." },
    { q: "Does deleting a secret in a later commit erase it from earlier history?", options: ["No", "Yes", "Only on Windows", "Only if the file was Markdown"], answer: 0, explain: "Earlier commits still contain the deleted content unless history is rewritten." },
    { q: "What is the first response to a real leaked token?", options: ["Revoke or rotate it", "Only rename the file", "Add a badge", "Open a public issue with the token"], answer: 0, explain: "A leaked secret should be treated as compromised." },
    { q: "Which pattern ignores packet captures?", options: ["*.pcap", "*.md", "*.html", "*.svg"], answer: 0, explain: "The *.pcap pattern ignores files ending in .pcap." },
    { q: "Which of these should never be committed, per the notes?", options: ["API keys, tokens, passwords, private keys, or recovery codes", "A sanitized README", "A generic checklist", "Learning notes"], answer: 0, explain: "The notes explicitly list these credential types as things never to commit." },
    { q: "Which of these should never be committed, per the notes?", options: [".env files with real credentials", "A public LICENSE file", "A sanitized lab writeup", "A safe screenshot"], answer: 0, explain: ".env files with real credentials are explicitly listed as unsafe to commit." },
    { q: "Which of these should never be committed, per the notes?", options: ["Packet captures from sensitive networks", "A generic README", "A public commit log", "A safe diagram"], answer: 0, explain: "Sensitive packet captures are explicitly called out as unsafe to commit." },
    { q: "Which of these should never be committed, per the notes?", options: ["Client data, internal IP lists, or vulnerable target details", "A sanitized methodology writeup", "A safe lessons-learned summary", "A generic checklist"], answer: 0, explain: "Client data and internal target details are explicitly listed as unsafe." },
    { q: "Which of these should never be committed, per the notes?", options: ["Malware samples or exploit code in a public repo", "A safe diagram", "A generic lab template", "A sanitized README"], answer: 0, explain: "Malware samples or exploit code in a public repo are explicitly listed as unsafe." },
    { q: "Which .gitignore pattern ignores private key files?", options: ["*.key", "*.pcap", "*.md", "*.html"], answer: 0, explain: "*.key matches private key files, per the notes' example .gitignore." },
    { q: "Which .gitignore pattern ignores PEM-formatted files?", options: ["*.pem", "*.svg", "*.md", "*.pcap"], answer: 0, explain: "*.pem matches PEM-formatted credential/certificate files." },
    { q: "Which .gitignore pattern ignores extended packet capture files?", options: ["*.pcapng", "*.pcap", "*.key", "*.pem"], answer: 0, explain: "*.pcapng matches the extended packet capture file format shown in the notes." },
    { q: "Which .gitignore entry would ignore a directory of private reports?", options: ["reports/private/", "reports/", "private.md", ".env"], answer: 0, explain: "reports/private/ is the exact entry shown in the notes' example .gitignore." },
    { q: "Which .gitignore entry would ignore a directory of evidence files?", options: ["evidence/", "evidence.md", "*.evidence", "logs/"], answer: 0, explain: "evidence/ is the exact entry shown in the notes' example .gitignore." },
    { q: "Does .gitignore remove a secret that was already committed?", options: ["No, it only prevents future untracked additions", "Yes, it deletes it from all history", "Yes, but only on GitHub", "No, but it encrypts it instead"], answer: 0, explain: "The notes state .gitignore does not remove secrets already committed." },
    { q: "What is the FIRST step if a secret was committed, per the notes?", options: ["Revoke or rotate the secret immediately", "Open a public issue about it", "Rename the file", "Add a badge to the README"], answer: 0, explain: "The notes list revoking or rotating the secret as the first response." },
    { q: "What is the step right after revoking or rotating a leaked secret, per the notes?", options: ["Remove the secret from the current files", "Delete the entire repository", "Publish the old secret for transparency", "Rename the branch"], answer: 0, explain: "After revoking/rotating, the notes say to remove the secret from current files." },
    { q: "What must you decide after removing a committed secret from current files?", options: ["Whether a history rewrite is needed", "Whether to rename the repository", "Whether to disable git entirely", "Whether to make the repo private forever"], answer: 0, explain: "The notes list deciding on a history rewrite as a next step." },
    { q: "Who should be notified after a secret leak, per the notes?", options: ["Anyone who may be affected", "No one, to avoid embarrassment", "Only the repository owner's manager", "The general public via social media"], answer: 0, explain: "The notes say to notify anyone who may be affected by the leak." },
    { q: "What should be added after handling a leaked secret incident, per the notes?", options: ["Prevention rules, and the process should be reviewed", "A public apology post", "A new README badge only", "Nothing further is needed"], answer: 0, explain: "The notes recommend adding prevention rules and reviewing the process afterward." },
    { q: "According to the warning in the notes, what happens if you delete a secret in a later commit?", options: ["It still exists in earlier Git history", "It is permanently erased everywhere", "It is automatically encrypted", "GitHub removes it from all forks instantly"], answer: 0, explain: "Deleting a file later does not erase it from earlier commits." },
    { q: "Why is a .env file with real credentials risky in a repo?", options: ["It exposes live credentials to anyone with repo access", "It slows down git clone", "It changes the default branch", "It disables .gitignore"], answer: 0, explain: "A committed .env with real credentials exposes them to anyone who can read the repo." },
    { q: "Why are packet captures from sensitive networks risky to commit?", options: ["They may contain sensitive traffic or internal data", "They make the repository larger only", "They break git log", "They are always encrypted automatically"], answer: 0, explain: "Packet captures can contain sensitive network traffic details." },
    { q: "Why is committing malware samples to a public repo dangerous?", options: ["It could spread or be misused by others", "It makes commits slower", "It requires a special file extension", "It automatically triggers a GitHub ban"], answer: 0, explain: "Publicly hosted malware samples could be downloaded and misused." },
    { q: "Which type of file does .gitignore act on to prevent accidental commits?", options: ["Untracked files", "Already-committed files", "Remote branches", "Pull requests"], answer: 0, explain: ".gitignore only affects untracked files, not ones already committed." },
    { q: "Which of these is NOT listed as an appropriate step after a secret leak, per the notes?", options: ["Publicly announce the old secret value for transparency", "Revoke or rotate the secret", "Notify anyone who may be affected", "Add prevention rules and review the process"], answer: 0, explain: "The notes never suggest publicizing the leaked secret value; the other three are actual steps." },
    { q: "Should you assume .gitignore protects files that are already tracked and committed?", options: ["No, .gitignore only applies to untracked files", "Yes, it retroactively removes them", "Yes, but only for .env files", "No, but it encrypts tracked files instead"], answer: 0, explain: ".gitignore has no effect on files Git is already tracking." },
    { q: "Which category of information includes \"internal IP lists\", per the notes?", options: ["Client data / sensitive target details that should never be committed", "Public documentation", "Safe lab templates", "Generic checklists"], answer: 0, explain: "Internal IP lists are grouped with client data and sensitive target details in the notes." },
    { q: "What is the overall goal of the \"if a secret was committed\" checklist in the notes?", options: ["To contain and remediate the exposure quickly and thoroughly", "To hide the incident from teammates", "To avoid rotating the secret", "To make the repository public"], answer: 0, explain: "The checklist exists to contain and fix a secret exposure as fast as possible." }
  ],
  "08": [
    { q: "What should a public cybersecurity lab writeup avoid?", options: ["Real credentials and sensitive identifiers", "Goals", "Lessons learned", "Safe commands"], answer: 0, explain: "Public writeups should be sanitized." },
    { q: "Why use Git for a lab journal?", options: ["To track learning over time", "To guarantee anonymity", "To replace all security tools", "To bypass authentication"], answer: 0, explain: "Git records progress and decisions." },
    { q: "What belongs in an incident timeline?", options: ["Events and actions in order", "Random passwords", "Private keys", "Unrelated jokes"], answer: 0, explain: "Timelines should organize evidence and response steps." },
    { q: "What is a portfolio-safe practice?", options: ["Publish sanitized methodology and lessons learned", "Publish client data", "Publish active exploit targets", "Publish raw secrets"], answer: 0, explain: "A portfolio should show skill without creating risk." },
    { q: "Where should sensitive evidence usually live?", options: ["Private, access-controlled storage", "A public GitHub repo", "A commit message", "A README badge"], answer: 0, explain: "Sensitive evidence needs access control." },
    { q: "In the lab journal folder structure, what would \"labs/nmap-baseline.md\" contain?", options: ["Documentation of a lab exercise", "A compiled binary", "A private key", "A GitHub access token"], answer: 0, explain: "Files under labs/ document lab exercises, per the example structure." },
    { q: "In the lab journal folder structure, what would \"scripts/parse-auth-log.py\" contain?", options: ["A script used in the workflow", "A packet capture", "A commit message", "A branch name"], answer: 0, explain: "Files under scripts/ hold scripts used in the workflow, like log parsers." },
    { q: "What should you do at each meaningful checkpoint in a lab journal, per the notes?", options: ["Commit it with a clear message", "Delete the previous commit", "Rename the branch", "Push directly to a stranger's fork"], answer: 0, explain: "The notes show committing at each meaningful checkpoint with a clear message." },
    { q: "Which command starts a branch for a mock phishing incident, per the notes?", options: ["git switch -c incident/phishing-timeline", "git branch phishing", "git merge incident/phishing-timeline", "git remote add incident/phishing-timeline"], answer: 0, explain: "The notes show this exact command for starting mock incident work." },
    { q: "Which of these should be tracked in an incident notes workflow, per the notes?", options: ["Timeline", "Router firmware version", "Wi-Fi password", "Screen resolution"], answer: 0, explain: "Timeline is one of the tracked items listed in the incident notes workflow." },
    { q: "Which of these should be tracked in an incident notes workflow, per the notes?", options: ["Indicators", "Font choice", "Repository color scheme", "Commit author's mood"], answer: 0, explain: "Indicators are one of the tracked items in the incident notes workflow." },
    { q: "Which of these should be tracked in an incident notes workflow, per the notes?", options: ["Evidence sources", "GitHub star count", "Branch protection rules", "Default browser"], answer: 0, explain: "Evidence sources are one of the tracked items in the incident notes workflow." },
    { q: "Which of these should be tracked in an incident notes workflow, per the notes?", options: ["Actions taken", "Repository license", "Font size", "Commit signature color"], answer: 0, explain: "Actions taken are one of the tracked items in the incident notes workflow." },
    { q: "Which of these should be tracked in an incident notes workflow, per the notes?", options: ["Open questions", "Wallpaper choice", "GitHub follower count", "Commit emoji"], answer: 0, explain: "Open questions are one of the tracked items in the incident notes workflow." },
    { q: "What does the Portfolio Workflow recommend publishing, per the notes?", options: ["Sanitized labs and writeups", "Raw client data", "Live exploit code", "Unredacted evidence"], answer: 0, explain: "The Portfolio Workflow recommends publishing sanitized labs and writeups." },
    { q: "What should a portfolio writeup explain, per the notes?", options: ["Methodology and lessons learned", "The victim's real identity", "Active exploit targets", "Internal network diagrams"], answer: 0, explain: "The notes say writeups should explain methodology and lessons learned." },
    { q: "What is recommended instead of posting raw sensitive data, per the notes?", options: ["Linking to safe screenshots or diagrams", "Encrypting it and posting anyway", "Posting it privately to strangers", "Uploading it to an anonymous forum"], answer: 0, explain: "The notes recommend linking to safe screenshots or diagrams instead of raw data." },
    { q: "Where should raw sensitive data stay, per the Portfolio Workflow?", options: ["Private", "In the README", "In commit messages", "In the public issue tracker"], answer: 0, explain: "Raw sensitive data should be kept private, per the notes." },
    { q: "According to the notes, what matters more than volume for a security portfolio?", options: ["Security judgment", "Number of repositories", "Number of followers", "Number of commits per day"], answer: 0, explain: "The notes state that security judgment matters more than volume." },
    { q: "What can GitHub become, according to the notes, if used carefully?", options: ["A portfolio", "A malware repository", "A replacement for all security tools", "An anonymous data dump"], answer: 0, explain: "The notes describe GitHub as a potential portfolio when used with good judgment." },
    { q: "Why use branches for mock incidents rather than committing directly to main, per the notes?", options: ["To isolate incident work as it develops", "Because main cannot accept commits", "Because branches are required by GitHub", "Because it deletes prior incidents automatically"], answer: 0, explain: "Branches keep in-progress incident work isolated until ready." },
    { q: "What is an example lab topic shown in the notes' folder structure?", options: ["wireshark-dns.md", "malware-binary.exe", "client-passwords.txt", "private-key.pem"], answer: 0, explain: "wireshark-dns.md is one of the example lab files shown in the notes." },
    { q: "What is an example lab topic shown in the notes' folder structure?", options: ["linux-hardening.md", "leaked-token.txt", "internal-ip-list.csv", "client-data.db"], answer: 0, explain: "linux-hardening.md is one of the example lab files shown in the notes." },
    { q: "What command sequence documents a completed lab step, per the notes?", options: ["git add labs/nmap-baseline.md, git commit -m \"Document Nmap baseline scan\"", "git clone labs/nmap-baseline.md", "git push labs/nmap-baseline.md", "git merge labs/nmap-baseline.md"], answer: 0, explain: "The notes show staging then committing the completed lab file." },
    { q: "What is the purpose of the \"notes/commands.md\" file in the example structure?", options: ["Keeping a running record of commands used", "Storing leaked credentials", "Holding the repository's private key", "Tracking GitHub billing"], answer: 0, explain: "notes/commands.md is shown as a place to record commands used." },
    { q: "Why should incident branches track \"open questions\", per the notes?", options: ["To document what still needs investigation", "To make the branch harder to merge", "To hide unresolved issues from teammates", "Because GitHub requires it"], answer: 0, explain: "Tracking open questions documents what still needs to be investigated." },
    { q: "Which workflow emphasizes showing skill without exposing unsafe material, per the notes?", options: ["Portfolio Workflow", "Lab Journal Workflow", "Incident Notes Workflow", "None of the workflows mention this"], answer: 0, explain: "The Portfolio Workflow is specifically about showing skill safely." },
    { q: "What is the risk of publishing unsanitized incident evidence publicly, per the notes?", options: ["It could expose sensitive or client data", "It automatically deletes the repository", "It breaks git log", "It disables branch protection"], answer: 0, explain: "Unsanitized evidence could expose sensitive or client information." },
    { q: "Which of these best summarizes the Lab Journal Workflow's purpose, per the notes?", options: ["Recording what you learned as you go", "Encrypting all lab files permanently", "Hiding lab results from reviewers", "Replacing incident response entirely"], answer: 0, explain: "The Lab Journal Workflow is about using Git to record what you learned." },
    { q: "Does more public repo volume automatically make a stronger security portfolio, per the notes?", options: ["No, judgment and safety matter more than volume", "Yes, more repos always means a stronger portfolio", "Yes, but only if they're all forks", "No, only paid GitHub accounts count"], answer: 0, explain: "The notes explicitly state judgment matters more than volume." }
  ]
};

QUESTIONS.mixed = Object.keys(QUESTIONS).flatMap((key) => QUESTIONS[key]);

function attemptSizeFor(topicId, total) {
  const configured = QUIZ_CONFIG.attempt[topicId] || QUIZ_CONFIG.defaultAttempt;
  return Math.min(configured, total);
}

function shuffleArray(items) {
  return [...items].sort(() => Math.random() - 0.5);
}

function pickProportionalMixed(count) {
  const chapterIds = TOPICS.map((topic) => topic.id).filter((id) => id !== "mixed");
  const sizes = chapterIds.map((id) => QUESTIONS[id].length);
  const totalBank = sizes.reduce((sum, size) => sum + size, 0);
  const raw = sizes.map((size) => (size / totalBank) * count);
  const quotas = raw.map((value) => Math.floor(value));
  let remaining = count - quotas.reduce((sum, quota) => sum + quota, 0);
  const remainderOrder = raw
    .map((value, index) => ({ index, frac: value - Math.floor(value) }))
    .sort((a, b) => b.frac - a.frac);
  for (let i = 0; i < remaining; i++) {
    quotas[remainderOrder[i].index] += 1;
  }
  const selected = chapterIds.flatMap((id, index) => shuffleArray(QUESTIONS[id]).slice(0, quotas[index]));
  return shuffleArray(selected);
}
